### PR TITLE
WIP: feat: add partitions support

### LINKED ISSUE #13: partition support
Role arn is using hard code partition `aws` to make it not to work in `aws-cn` and gov us partition.

### PR DESCRIPTION
**Pull request by zxkane**
*Issue #, if available:*

closes #13 

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by corymhall** [comment]
@zxkane it doesn't look like the `CDK_DEFAULT_REGION` has been set by the CDK at the time plugins are called. You might have to rely on a context variable like we are doing here. This context variable `region` is not set by default, it will need to be set by the user.

https://github.com/aws-samples/cdk-assume-role-credential-plugin/blob/821594ee011a19867f987fa5a08c0ffa08e176d9/lib/assume-role-source.ts#L210

**Comment by zxkane** [comment]
> @zxkane it doesn't look like the `CDK_DEFAULT_REGION` has been set by the CDK at the time plugins are called. You might have to rely on a context variable like we are doing here. This context variable `region` is not set by default, it will need to be set by the user.
> 
> https://github.com/aws-samples/cdk-assume-role-credential-plugin/blob/821594ee011a19867f987fa5a08c0ffa08e176d9/lib/assume-role-source.ts#L210

@corymhall thanks for the hint. Updating the PR to fetch region info from the `region` context parameter. With the verbose log, I did see this credential plugin was using the correct role arn to be assumed.

But the deployment still fails on looking up the existing vpc via vpc id and existing hosted zone via hosted zone id.

The snippet verbose output of cdk,
```
AssumeRoleCredentialPlugin found value for readIamRole opentuna-deployment-trust-034068960xxx-role. checking if we can obtain credentials
AssumeRoleCredentialPlugin rolearn is arn:aws-cn:iam::1821957475xx:role/opentuna-deployment-trust-034068960xxx-role
Setting "vpc-provider:account=1821957475xx:filter.vpc-id=vpc-0cf564c2896ddec25:region=cn-northwest-1:returnAsymmetricSubnets=true" context to {"$providerError":"EC2 Metadata roleName request returned error","$dontSaveContext":true}
Reading hosted zone 1821957475xx:mydomain.com
AssumeRoleCredentialPlugin found value for readIamRole opentuna-deployment-trust-034068960xxx-role. checking if we can obtain credentials
AssumeRoleCredentialPlugin rolearn is arn:aws-cn:iam::1821957475xx:role/opentuna-deployment-trust-034068960xxx-role
Setting "hosted-zone:account=1821957475xx:domainName=mydomain.com:region=cn-northwest-1" context to {"$providerError":"EC2 Metadata roleName request returned error","$dontSaveContext":true}
```

However the assuming same role works fine in cli via `aws sts assume-role`.

Any suggestion for it.

**Comment by corymhall** [comment]
From the error message it looks like it might be an issue might be with the default credentials. Can you provide more information on what you local environment looks like? Are your local credentials set in `~/.aws/credentials` or are you on an EC2 instance and using the instance profile, or using a profile configured in `~/.aws/config` etc.

**Comment by zxkane** [comment]
I’m deploying the cdk app in local env. The credentials is configured via the awscli way `~/.aws/credentials`. And I have multiple profiles defined in `~/.aws/config`.

Usually I specify the active profile via env `export AWS_DEFAULT_PROFILE=my-profile-name` before running cdk command.

**Comment by corymhall** [comment]
Should be fixed in v1.3.0.

**Pull request closed without merging**
